name: HTTP Cron Tetikleyicisi

on:
  schedule:
    - cron: "* * * * *"   # her dakika (UTC)
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Trigger remote cron
        run: |
          curl --fail --silent --show-error \
          -A "GITHUB-SCHEDULE-CRON" \
          https://salonazizcan.hedefbilgitoplumu.com/cron.php
